  test:
    needs: lint
    timeout-minutes: 60
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        browser: [chromium, firefox, webkit, 'Mobile Safari']
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: lts/*
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

+     - name: Restore auth state file
+       run: |
+         mkdir -p .auth
+         echo "${{ secrets.EXISTING_USER_AUTH_B64 }}" | base64 -d > .auth/user.json

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps
      - name: Run Playwright tests
        run: npx playwright test --project="${{ matrix.browser }}"